apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: base-ope-image
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: >-
      https://quay.io/repository/opeffort/nerc
    opendatahub.io/notebook-image-name: >-
      Base OPE Image
    opendatahub.io/notebook-image-desc: |-
      Base OPE Image used for Open Education classes.
      Provides a standardized environment for notebooks.
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: quay.io/opeffort/nerc:beta-base-ope-image
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
