apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cuda-jupyter-langchain
  namespace: redhat-ods-applications
  labels:
    # app.kubernetes.io/created-by: ''
    app.kubernetes.io/part-of: workbenches
    app.opendatahub.io/workbenches: 'true'
    component.opendatahub.io/name: notebooks
    opendatahub.io/component: 'true'
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
  annotations:
    opendatahub.io/notebook-image-url: >-
      quay.io/opendatahub-contrib/workbench-images:cuda-jupyter-langchain-c9s-py311_2023c_latest
    opendatahub.io/notebook-image-name: >-
      Jupyter Langchain CUDA
    opendatahub.io/notebook-image-desc: |-
      A Jupyter OpenShift AI Image with Langchain and CUDA for GPUs.
      Based on the [opendatahub workbench images](https://github.com/opendatahub-io-contrib/workbench-images)
      on GitHub for Jupyter Lab Notebook integration.
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations:
        # opendatahub.io/notebook-build-commit: 'xyz'
        opendatahub.io/notebook-python-dependencies: '[{"name":"Python","version":"v3.11","visible":true}]'
        opendatahub.io/notebook-software: '[{"name":"CUDA","version":"11.8","visible":true}]'
        opendatahub.io/workbench-image-recommended: 'false'
        openshift.io/imported-from: 'quay.io/opendatahub-contrib/workbench-images:cuda-jupyter-langchain-c9s-py311_2023c_latest'
      from:
        kind: DockerImage
        name: 'quay.io/opendatahub-contrib/workbench-images:cuda-jupyter-langchain-c9s-py311_2023c_latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
