apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: odh-tec
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: >-
      https://github.com/rh-aiservices-bu/odh-tec/
    opendatahub.io/notebook-image-name: >-
      ODH-TEC
    opendatahub.io/notebook-image-desc: |-
      Open Data Hub Tools & Extensions Companion (ODH-TEC) application
      implements a unified storage management platform and tools that
      can be useful to anyone working with Open Data Hub (ODH), Red Hat
      OpenShift AI (RHOAI), or even locally with Podman. It supports
      both S3-compatible object storage and local filesystem storage
      (PVC mounts), providing seamless file management across different
      storage types.
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/rh-aiservices-bu/odh-tec:latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
